server:
  port: 5000
shiro:
  bots:
    bot-id: ${bots.bot-id}
  ws:
    client:
      enable: true
      url: ${bots.ws-url}

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.url:localhost}
    username: ${mysql.username:root}
    password: ${mysql.password:password}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.liahnu.bot.model.domain
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
