name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
      - develop/ci #  当推送到 develop/ci 分支时触发

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1️⃣ 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ 设置 JDK 17 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3️⃣ 缓存 Gradle 包
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        shell: bash

      # 4️⃣ 安装依赖
      - name: Install dependencies
        run: ./gradlew --no-daemon --refresh-dependencies

      # 5️⃣ 执行测试
      - name: Run tests
        run: ./gradlew test

      - name: Login  to GITHUB  Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GITHUB_TOKEN }}

      # 6️⃣ 构建 Docker 镜像
      - name: Build Docker image
        run: ./gradlew dockerBuildImage

      - name: Docker push image
        run: ./gradlew dockerPushImage